const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
let state=Engine.create(LEVEL),keys={},pressed={},paused=false,loaded=false,muted=false,last=0,acc=0,noticeTimer=0;
const art={},overlay=document.getElementById('overlay'),start=document.getElementById('start'),status=document.getElementById('status');
const initialLives=document.getElementById('initial-lives');
try{const saved=localStorage.getItem('contra-initial-lives');if([...initialLives.options].some(o=>o.value===saved))initialLives.value=saved;}catch{}
initialLives.onchange=()=>{try{localStorage.setItem('contra-initial-lives',initialLives.value);}catch{}notice('初始生命：'+initialLives.value+' 条，下次开局生效。');};
const music=new Audio('assets/main_theme.mp3');music.loop=true;music.volume=.18;
const sounds={};for(const [name,file]of Object.entries({pistol:'rossi_shot',machine:'rossi_shot_HM',rocket:'rossi_shot_HM',explosion:'explosion',death:'Marco_Rossi_Death',complete:'mission_complete',pickup:'metal_slug_HM'}))sounds[name]=new Audio('assets/'+file+'.mp3');
function sound(name){if(muted||!sounds[name])return;const a=sounds[name].cloneNode();a.volume=name==='machine'?.13:.26;a.play().catch(()=>{});}
function notice(text){status.textContent=text;noticeTimer=120;}
function modal(title,copy,label){document.getElementById('overlay-title').textContent=title;document.getElementById('overlay-copy').textContent=copy;start.textContent=label;overlay.hidden=false;}
function begin(){if(!loaded)return;if(paused){paused=false;overlay.hidden=true;}else{if(state.phase==='dead'&&state.lives>0){state=Engine.respawn(state);}else{state=Engine.create(LEVEL);state.lives=Number(initialLives.value);}state.phase='playing';overlay.hidden=true;music.currentTime=0;}keys={};pressed={};acc=0;canvas.focus();if(!muted)music.play().catch(()=>{});notice('穿越丛林，摧毁关底堡垒。');}
function pause(){if(state.phase!=='playing')return;paused=!paused;keys={};pressed={};if(paused){music.pause();modal('行动暂停','按 P 或点击继续，回到战场。','继续行动');status.textContent='已暂停';}else{overlay.hidden=true;canvas.focus();if(!muted)music.play().catch(()=>{});}}
start.onclick=begin;document.getElementById('restart').onclick=()=>{paused=false;state=Engine.create(LEVEL);begin();};
document.getElementById('sound').onclick=()=>{muted=!muted;music.muted=muted;document.getElementById('sound').textContent='声音：'+(muted?'关':'开');document.getElementById('sound').setAttribute('aria-pressed',String(muted));if(!muted&&state.phase==='playing'&&!paused)music.play().catch(()=>{});};
document.getElementById('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.getElementById('screen').requestFullscreen();}catch{notice('可放大浏览器窗口试玩。');}};
document.querySelectorAll('[data-weapon]').forEach(b=>b.onclick=()=>{if(state.phase==='playing'&&!paused){Engine.choose(state,+b.dataset.weapon);notice(Engine.guns[state.weapon].name);canvas.focus();}});
const valid=['ArrowLeft','ArrowRight','ArrowDown','ArrowUp','KeyA','KeyD','KeyS','KeyW','KeyK','Space','KeyJ','KeyL','KeyQ','Digit1','Digit2','Digit3'];
function key(code,down){if(down&&!keys[code])pressed[code]=true;keys[code]=down;}
window.addEventListener('keydown',e=>{if(e.target===initialLives)return;if(valid.includes(e.code)){e.preventDefault();key(e.code,true);}if(e.code==='KeyP'&&!e.repeat){e.preventDefault();pause();}if(e.code==='Enter'&&!overlay.hidden){e.preventDefault();begin();}});
window.addEventListener('keyup',e=>{if(valid.includes(e.code)){e.preventDefault();key(e.code,false);}});
window.addEventListener('blur',()=>{keys={};pressed={};if(!paused&&state.phase==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&!paused&&state.phase==='playing')pause();});
document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);key(b.dataset.key,true);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>key(b.dataset.key,false);});
function load(name,path){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{art[name]=img;resolve();};img.onerror=()=>reject(new Error(path));img.src=path;});}
function sprite(img,sx,sy,sw,sh,x,y,w=sw,h=sh){ctx.drawImage(img,sx,sy,sw,sh,Math.round(x),Math.round(y),w,h);}
function marco(){const p=state.p;if(p.inv&&Math.floor(state.frame/5)%2)return;ctx.save();ctx.translate(Math.round(p.x-state.camera+8),Math.round(p.y+p.h));ctx.scale(p.dir*.8,.8);
  if(state.phase==='dead'){const n=Math.min(16,Math.floor(state.deadTicks/5));sprite(art.marco,n*40,216,40,41,-20,-41);ctx.restore();return;}
  const crouched=p.h===20,frame=p.grounded?(Math.abs(p.vx)>.1?4+Math.floor(state.frame/4)%19:Math.floor(state.frame/9)%4):4+Math.floor(state.frame/5)%12;
  if(!p.swimming)sprite(art.marco,frame*34,p.grounded?0:49,34,48,-17,-48,34,crouched?38:48);
  const y=crouched?-25:-39;const heavy=state.weapon>0;
  if(p.shot){const n=Math.floor((8-p.shot)/2)%(heavy?5:10);sprite(art.marco,n*120,heavy?186:126,120,30,heavy?-55:-57,y);}
  else{const n=Math.floor(state.frame/9)%4;sprite(art.marco,n*(heavy?40:34),heavy?156:96,heavy?40:34,30,heavy?-15:-14,y);}
  if(state.weapon===2){ctx.fillStyle='#383b25';ctx.fillRect(4,y+13,26,7);ctx.fillStyle='#a0a66c';ctx.fillRect(6,y+13,22,2);ctx.fillStyle='#232722';ctx.fillRect(26,y+11,5,11);}
  ctx.restore();
}
function hud(){ctx.textBaseline='top';ctx.font='8px Pixel,monospace';ctx.fillStyle='#ffe4a0';ctx.fillText('MARCO',12,10);ctx.fillText('ARMS',110,10);ctx.fillText('BOMB',198,10);ctx.fillText('1-1',284,10);ctx.fillStyle='#fff';ctx.fillText('LIFE '+state.lives,12,21);ctx.fillText(state.weapon===0?'INFINITY':String(state.ammo[state.weapon]),110,21);ctx.fillText(String(state.grenades).padStart(2,'0'),206,21);ctx.fillText(String(state.score).padStart(6,'0'),260,21);}
function render(){if(!loaded)return;sprite(art.map,512+state.camera,0,320,240,0,0);
  for(const b of state.platforms)if(b.bridge&&b.gone){ctx.fillStyle='#0070e8';ctx.fillRect(b.x-state.camera,112,16,32);}
  for(const b of state.pickups)if(!b.taken){const x=b.x-state.camera;ctx.fillStyle='#e9bc45';ctx.fillRect(x,b.y,16,15);ctx.fillStyle='#403613';ctx.fillRect(x+2,b.y+2,12,11);ctx.fillStyle='#ffe6a2';ctx.font='8px Pixel';ctx.fillText(b.kind==='ammo'?'H':'G',x+4,b.y+3);}
  for(const e of state.enemies){if(e.kind==='core'||e.kind==='bossGun'){const x=e.x-state.camera;ctx.fillStyle='#222532';ctx.fillRect(x,e.y,e.w,e.h);ctx.strokeStyle=e.flash?'#fff':'#a7a9bf';ctx.strokeRect(x+.5,e.y+.5,e.w-1,e.h-1);if(e.hp>0){if(e.kind==='core'){ctx.fillStyle=e.flash?'#fff':Math.floor(state.frame/12)%2?'#ea673b':'#b84132';ctx.fillRect(x+5,e.y+5,e.w-10,e.h-10);ctx.fillStyle='#ffc478';ctx.fillRect(x+9,e.y+10,5,10);}else{ctx.fillStyle='#565b75';ctx.fillRect(x+5,e.y+4,12,12);ctx.fillStyle='#b9bace';ctx.fillRect(x-5,e.y+7,16,5);ctx.fillStyle='#10131c';ctx.fillRect(x-5,e.y+8,4,3);}}continue;}if(e.hp<=0||e.x<state.camera-40||e.x>state.camera+340)continue;ctx.save();if(e.flash)ctx.filter='brightness(3)';if(e.kind==='turret')sprite(art.turret,0,0,32,32,e.x-state.camera,e.y);else sprite(art.soldier,Math.floor(state.frame/6)%LEVEL.soldierFrames*16,0,16,32,e.x-state.camera,e.y);ctx.restore();}
  marco();
  for(const b of state.shots){const x=Math.round(b.x-state.camera),y=Math.round(b.y);if(b.kind==='grenade'){ctx.fillStyle='#121b0f';ctx.fillRect(x,y,6,6);ctx.fillStyle='#bbc684';ctx.fillRect(x+1,y,4,4);}else if(b.kind==='rocket'){ctx.fillStyle='#d8d3b9';ctx.fillRect(x,y,9,4);ctx.fillStyle='#ff9827';ctx.fillRect(x-(b.vx>=0?5:-9),y+1,5,2);}else{ctx.fillStyle=b.weapon===1?'#ffd36e':'#fff3c9';ctx.fillRect(x,y,b.weapon===1?9:5,2);}}
  for(const b of state.enemyShots){ctx.fillStyle='#ff5838';ctx.fillRect(Math.round(b.x-state.camera),Math.round(b.y),4,4);ctx.fillStyle='#ffeaa1';ctx.fillRect(Math.round(b.x-state.camera+1),Math.round(b.y+1),2,2);}
  for(const e of state.effects){const n=Math.min(27,2+Math.floor((38-e.ttl)*.75));sprite(art.explosion,n*80,0,80,80,e.x-state.camera-e.size/2,e.y-e.size/2,e.size,e.size);}
  hud();if(state.bossActive){const boss=state.enemies.find(e=>e.kind==='core');ctx.fillStyle='#151723';ctx.fillRect(80,37,160,11);ctx.fillStyle='#e86843';ctx.fillRect(82,39,156*Math.max(0,boss.hp)/boss.maxHp,7);ctx.fillStyle='#fff';ctx.font='6px Pixel';ctx.fillText('FORTRESS',136,51);}document.querySelectorAll('[data-weapon]').forEach(b=>{const id=+b.dataset.weapon;b.classList.toggle('selected',id===state.weapon);b.setAttribute('aria-pressed',String(id===state.weapon));document.getElementById('ammo'+id).textContent=id===0?'∞':state.ammo[id];});document.getElementById('grenades').textContent=state.grenades;
}
function loop(now){if(!last)last=now;acc+=Math.min(100,now-last);last=now;while(acc>=1000/60){if(!paused){const before=state.phase;Engine.tick(state,{left:keys.ArrowLeft||keys.KeyA,right:keys.ArrowRight||keys.KeyD,up:keys.ArrowUp,down:keys.ArrowDown||keys.KeyS,jump:keys.Space||keys.KeyK||keys.KeyW,jumpPressed:pressed.Space||pressed.KeyK||pressed.KeyW,fire:keys.KeyJ||pressed.KeyJ,grenade:pressed.KeyL,cycle:pressed.KeyQ,select:pressed.Digit1?0:pressed.Digit2?1:pressed.Digit3?2:undefined});pressed={};state.events.forEach(sound);if(state.events.includes('fallback'))notice('弹药耗尽，已自动切回手枪。');if(state.events.includes('switch'))notice('已切换：'+Engine.guns[state.weapon].name);if(state.events.includes('empty'))notice('弹药不足，选择其他武器。');if(state.events.includes('pickup'))notice('补给已收取。');if(noticeTimer>0)noticeTimer--;else if(state.phase==='playing')status.textContent=state.p.swimming?'水中：向上射击，跳出水面。':state.bossActive?'堡垒核心在下方：跳下平台，集中火力！':state.p.x>=768&&state.p.x<1184?'桥在爆破，继续向右冲！':'Q 切换武器 · L 投掷手榴弹';
    if(before!==state.phase){music.pause();keys={};if(state.phase==='complete'){status.textContent='第一关完成';modal('MISSION COMPLETE',`堡垒已摧毁！得分 ${state.score} · 击败 ${state.kills} 个敌人。第一关丛林行动完成。`,'再闯一次');}}
    if(state.phase==='dead'&&state.deadTicks===90){modal(state.lives?'重新集结。':'GAME OVER',state.lives?`还剩 ${state.lives} 条命，从最近检查点补满装备继续。`:'再试一次，重机枪适合压制，火箭适合炮台。',state.lives?'继续行动':'重新开始');}
  }acc-=1000/60;}render();requestAnimationFrame(loop);}
Promise.all([load('map','assets/contra-stage1.png'),load('marco','assets/marco.png'),load('soldier','assets/soldier.png'),load('turret','assets/turret.png'),load('explosion','assets/explosion.png'),document.fonts.ready]).then(()=>{loaded=true;start.disabled=false;start.textContent='开始行动 →';render();requestAnimationFrame(loop);}).catch(e=>{status.textContent='素材加载失败：'+e.message;console.error(e);});
